"""followers

Revision ID: 30da2ef873d5
Revises: dd20f7f3d86f
Create Date: 2020-06-27 17:20:11.227871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30da2ef873d5'
down_revision = 'dd20f7f3d86f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
